apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-interface-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-interface
  template:
    metadata:
      labels:
        app: web-interface
    spec:
      containers:
        - name: web-interface
          image: web-interface:v1
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "100Mi"
              cpu: "200m"
            limits:
              memory: "500Mi"
              cpu: "500m"
