apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-service
  template:
    metadata:
      labels:
        app: api-service
    spec:
      containers:
        - name: api-service
          image: api-service:v1
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: api-service-config  # Наименование моего ConfigMap
            - secretRef:
                name: api-service-secret  # Наименование моего Secret
          resources:
            requests:
              memory: "100Mi"
              cpu: "200m"
            limits:
              memory: "500Mi"
              cpu: "500m"


# Пример:
          envFrom:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: api-service-config
                  key: DATABASE_URL
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: api-service-config
                  key: DB_HOST
            # Добавляем другие переменные из ConfigMap'а
            - name: OTHER_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: api-service-config
                  key: OTHER_CONFIG
            # Пример использования переменных из секрета
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: api-service-secret
                  key: secret-key
