apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-service
  template:
    metadata:
      labels:
        app: api-service
    spec:
      containers:
        - name: api-service
          image: api-service:v1
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: api-service-config  # Наименование моего ConfigMap
            - secretRef:
                name: api-service-secret  # Наименование моего Secret
          resources:
            requests:
              memory: "100Mi"
              cpu: "200m"
            limits:
              memory: "500Mi"
              cpu: "500m"
